package ste.cipeciop.dao.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Ciop was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Ciop extends CayenneDataObject {

    public static final String CREATED_PROPERTY = "created";
    public static final String FLAGS_PROPERTY = "flags";
    public static final String FROM_PROPERTY = "from";
    public static final String ID_PROPERTY = "id";
    public static final String SEEN_PROPERTY = "seen";
    public static final String TEXT_PROPERTY = "text";
    public static final String TO_PROPERTY = "to";

    public static final String ID_PK_COLUMN = "id";

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setFlags(int flags) {
        writeProperty("flags", flags);
    }

    public int getFlags() {
        Object value = readProperty("flags");
        return (value != null) ? (Integer) value : 0;
    }


    public void setFrom(String from) {
        writeProperty("from", from);
    }

    public String getFrom() {
        return (String)readProperty("from");
    }

    public void setId(int id) {
        writeProperty("id", id);
    }

    public int getId() {
        Object value = readProperty("id");
        return (value != null) ? (Integer) value : 0;
    }

    public void setSeen(Date seen) {
        writeProperty("seen", seen);
    }

    public Date getSeen() {
        return (Date)readProperty("seen");
    }

    public void setText(String text) {
        writeProperty("text", text);
    }

    public String getText() {
        return (String)readProperty("text");
    }

    public void setTo(String to) {
        writeProperty("to", to);
    }

    public String getTo() {
        return (String)readProperty("to");
    }

}
