package ste.cipeciop.dao.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Cip was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Cip extends CayenneDataObject {

    public static final String FROM_PROPERTY = "from";
    public static final String ID_PROPERTY = "id";
    public static final String TEXT_PROPERTY = "text";
    public static final String TO_PROPERTY = "to";
    public static final String WHEN_PROPERTY = "when";

    public static final String ID_PK_COLUMN = "id";

    public void setFrom(String from) {
        writeProperty("from", from);
    }
    public String getFrom() {
        return (String)readProperty("from");
    }

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setText(String text) {
        writeProperty("text", text);
    }
    public String getText() {
        return (String)readProperty("text");
    }

    public void setTo(String to) {
        writeProperty("to", to);
    }
    public String getTo() {
        return (String)readProperty("to");
    }

    public void setWhen(long when) {
        writeProperty("when", when);
    }
    public long getWhen() {
        Object value = readProperty("when");
        return (value != null) ? (Long) value : 0;
    }

}
